In [1]:
import pandas as pd 
import matplotlib.pyplot as plt 
import numpy as np 
import seaborn as sns
%matplotlib inline

In [4]:
df = pd.read_csv('candy-data.csv')

In [5]:
df.head()

competitorname  chocolate  fruity  caramel  peanutyalmondy  nougat  \
0      100 Grand          1       0        1               0       0   
1   3 Musketeers          1       0        0               0       1   
2       One dime          0       0        0               0       0   
3    One quarter          0       0        0               0       0   
4      Air Heads          0       1        0               0       0   

   crispedricewafer  hard  bar  pluribus  sugarpercent  pricepercent  \
0                 1     0    1         0         0.732         0.860   
1                 0     0    1         0         0.604         0.511   
2                 0     0    0         0         0.011         0.116   
3                 0     0    0         0         0.011         0.511   
4                 0     0    0         0         0.906         0.511   

   winpercent  
0   66.971725  
1   67.602936  
2   32.261086  
3   46.116505  
4   52.341465

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85 entries, 0 to 84
Data columns (total 13 columns):
competitorname      85 non-null object
chocolate           85 non-null int64
fruity              85 non-null int64
caramel             85 non-null int64
peanutyalmondy      85 non-null int64
nougat              85 non-null int64
crispedricewafer    85 non-null int64
hard                85 non-null int64
bar                 85 non-null int64
pluribus            85 non-null int64
sugarpercent        85 non-null float64
pricepercent        85 non-null float64
winpercent          85 non-null float64
dtypes: float64(3), int64(9), object(1)
memory usage: 8.8+ KB


In [7]:
df.describe()

chocolate     fruity    caramel  peanutyalmondy     nougat  \
count  85.000000  85.000000  85.000000       85.000000  85.000000   
mean    0.435294   0.447059   0.164706        0.164706   0.082353   
std     0.498738   0.500140   0.373116        0.373116   0.276533   
min     0.000000   0.000000   0.000000        0.000000   0.000000   
25%     0.000000   0.000000   0.000000        0.000000   0.000000   
50%     0.000000   0.000000   0.000000        0.000000   0.000000   
75%     1.000000   1.000000   0.000000        0.000000   0.000000   
max     1.000000   1.000000   1.000000        1.000000   1.000000   

       crispedricewafer       hard        bar   pluribus  sugarpercent  \
count         85.000000  85.000000  85.000000  85.000000     85.000000   
mean           0.082353   0.176471   0.247059   0.517647      0.478647   
std            0.276533   0.383482   0.433861   0.502654      0.282778   
min            0.000000   0.000000   0.000000   0.000000      0.011000   
25%            0.000000   0.000000   0.000000   0.000000      0.220000   
50%            0.000000   0.000000   0.000000   1.000000      0.465000   
75%            0.000000   0.000000   0.000000   1.000000      0.732000   
max            1.000000   1.000000   1.000000   1.000000      0.988000   

       pricepercent  winpercent  
count     85.000000   85.000000  
mean       0.468882   50.316764  
std        0.285740   14.714357  
min        0.011000   22.445341  
25%        0.255000   39.141056  
50%        0.465000   47.829754  
75%        0.651000   59.863998  
max        0.976000   84.180290

In [9]:

df.drop("competitorname", inplace = True, axis=1)


In [14]:
y = df['chocolate'].values
X = df.drop(["chocolate"], axis = 1)
X


fruity  caramel  peanutyalmondy  nougat  crispedricewafer  hard  bar  \
0        0        1               0       0                 1     0    1   
1        0        0               0       1                 0     0    1   
2        0        0               0       0                 0     0    0   
3        0        0               0       0                 0     0    0   
4        1        0               0       0                 0     0    0   
..     ...      ...             ...     ...               ...   ...  ...   
80       1        0               0       0                 0     0    0   
81       1        0               0       0                 0     1    0   
82       1        0               0       0                 0     0    0   
83       0        1               0       0                 0     1    0   
84       0        0               0       0                 1     0    0   

    pluribus  sugarpercent  pricepercent  winpercent  
0          0         0.732         0.860   66.971725  
1          0         0.604         0.511   67.602936  
2          0         0.011         0.116   32.261086  
3          0         0.011         0.511   46.116505  
4          0         0.906         0.511   52.341465  
..       ...           ...           ...         ...  
80         0         0.220         0.116   45.466282  
81         0         0.093         0.116   39.011898  
82         1         0.313         0.313   44.375519  
83         0         0.186         0.267   41.904308  
84         1         0.872         0.848   49.524113  

[85 rows x 11 columns]

In [20]:
# standrization 
X = (X - np.mean(X)) / (np.std(X))

In [21]:
X.describe()

fruity       caramel  peanutyalmondy        nougat  \
count  8.500000e+01  8.500000e+01    8.500000e+01  8.500000e+01   
mean   1.828603e-17 -7.314411e-17   -9.534857e-17  5.224579e-18   
std    1.005935e+00  1.005935e+00    1.005935e+00  1.005935e+00   
min   -8.991722e-01 -4.440530e-01   -4.440530e-01 -2.995723e-01   
25%   -8.991722e-01 -4.440530e-01   -4.440530e-01 -2.995723e-01   
50%   -8.991722e-01 -4.440530e-01   -4.440530e-01 -2.995723e-01   
75%    1.112134e+00 -4.440530e-01   -4.440530e-01 -2.995723e-01   
max    1.112134e+00  2.251983e+00    2.251983e+00  3.338092e+00   

       crispedricewafer          hard           bar      pluribus  \
count      8.500000e+01  8.500000e+01  8.500000e+01  8.500000e+01   
mean      -4.179663e-17  2.220446e-17  3.395976e-17  1.854726e-16   
std        1.005935e+00  1.005935e+00  1.005935e+00  1.005935e+00   
min       -2.995723e-01 -4.629100e-01 -5.728220e-01 -1.035940e+00   
25%       -2.995723e-01 -4.629100e-01 -5.728220e-01 -1.035940e+00   
50%       -2.995723e-01 -4.629100e-01 -5.728220e-01  9.653073e-01   
75%       -2.995723e-01 -4.629100e-01 -5.728220e-01  9.653073e-01   
max        3.338092e+00  2.160247e+00  1.745743e+00  9.653073e-01   

       sugarpercent  pricepercent    winpercent  
count  8.500000e+01  8.500000e+01  8.500000e+01  
mean  -7.053182e-17  7.053182e-17  1.510230e-17  
std    1.005935e+00  1.005935e+00  1.005935e+00  
min   -1.663576e+00 -1.611956e+00 -1.905407e+00  
25%   -9.200934e-01 -7.529642e-01 -7.640179e-01  
50%   -4.854709e-02 -1.366766e-02 -1.700224e-01  
75%    9.012605e-01  6.411379e-01  6.526887e-01  
max    1.811937e+00  1.785287e+00  2.315052e+00

In [22]:
df.columns

Index(['chocolate', 'fruity', 'caramel', 'peanutyalmondy', 'nougat',
       'crispedricewafer', 'hard', 'bar', 'pluribus', 'sugarpercent',
       'pricepercent', 'winpercent'],
      dtype='object')

In [23]:
cols = ['fruity', 'caramel', 'peanutyalmondy', 'nougat',
       'crispedricewafer', 'hard', 'bar', 'pluribus', 'sugarpercent',
       'pricepercent', 'winpercent']

In [72]:
for col in cols:
    print(f'skweness is:{df[col].skew()}')

skweness is:0.21680674820119522
skweness is:1.8405714321841782
skweness is:1.840571432184178
skweness is:3.0933783444728986
skweness is:3.093378344472898
skweness is:1.7279813604151597
skweness is:1.1940976254927538
skweness is:-0.07190746881936465
skweness is:0.0954157296808263
skweness is:0.1326238228512534
skweness is:0.3323127567334607


In [26]:
X

fruity   caramel  peanutyalmondy    nougat  crispedricewafer      hard  \
0  -0.899172  2.251983       -0.444053 -0.299572          3.338092 -0.462910   
1  -0.899172 -0.444053       -0.444053  3.338092         -0.299572 -0.462910   
2  -0.899172 -0.444053       -0.444053 -0.299572         -0.299572 -0.462910   
3  -0.899172 -0.444053       -0.444053 -0.299572         -0.299572 -0.462910   
4   1.112134 -0.444053       -0.444053 -0.299572         -0.299572 -0.462910   
..       ...       ...             ...       ...               ...       ...   
80  1.112134 -0.444053       -0.444053 -0.299572         -0.299572 -0.462910   
81  1.112134 -0.444053       -0.444053 -0.299572         -0.299572  2.160247   
82  1.112134 -0.444053       -0.444053 -0.299572         -0.299572 -0.462910   
83 -0.899172  2.251983       -0.444053 -0.299572         -0.299572  2.160247   
84 -0.899172 -0.444053       -0.444053 -0.299572          3.338092 -0.462910   

         bar  pluribus  sugarpercent  pricepercent  winpercent  
0   1.745743 -1.035940      0.901261      1.376914    1.138603  
1   1.745743 -1.035940      0.445922      0.148273    1.181755  
2  -0.572822 -1.035940     -1.663576     -1.242308   -1.234361  
3  -0.572822 -1.035940     -1.663576      0.148273   -0.287147  
4  -0.572822 -1.035940      1.520236      0.148273    0.138417  
..       ...       ...           ...           ...         ...  
80 -0.572822 -1.035940     -0.920093     -1.242308   -0.331599  
81 -0.572822 -1.035940     -1.371875     -1.242308   -0.772848  
82 -0.572822  0.965307     -0.589262     -0.548778   -0.406168  
83 -0.572822 -1.035940     -1.041043     -0.710719   -0.575111  
84 -0.572822  0.965307      1.399287      1.334668   -0.054189  

[85 rows x 11 columns]

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression


In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25,random_state = 1)


In [33]:
clf = LogisticRegression(random_state = 1)
clf.fit(X_train, y_train)

F:\anaconda_installation\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=1, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [35]:
y_pred = clf.predict(X_test)
y_pred

array([1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1],
      dtype=int64)

In [48]:
from sklearn.metrics import confusion_matrix, f1_score

confusion_matrix(y_test,y_pred)


array([[12,  0],
       [ 0, 10]], dtype=int64)

In [49]:
from sklearn.metrics import mean_squared_error

In [50]:
f1_score(y_test,y_pred)


1.0

In [56]:
from sklearn.metrics import mean_squared_error
rms = np.sqrt(mean_squared_error(y_test,y_pred))
print('rms Error :',rms)



rms Error : 0.0


In [59]:
y_test

array([1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1],
      dtype=int64)

In [60]:
y_pred

array([1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1],
      dtype=int64)

In [61]:
y

array([1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1],
      dtype=int64)